executor: KubernetesExecutor

airflow:
  image:
    repository: apache/airflow
    tag: 3.0.2

  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/Harish2f/financial-decision-system.git
    branch: main
    rev: HEAD
    subPath: dags
    depth: 1
    wait: 30
    period: 30s
    ref: HEAD

postgresql:
  enabled: true
  image:
    registry: financialairegistry.azurecr.io
    repository: postgresql
    tag: "15"

redis:
  enabled: false