name: Deploy Financial Decision System

on:
  workflow_run:
    workflows: ["Finance AI CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Debug registry variables
        run: |
          echo "ACR_NAME = ${{ secrets.ACR_NAME }}"
          echo "IMAGE_NAME = ${{ secrets.IMAGE_NAME }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}
            ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest

      - name: Debug AKS secrets
        run: |
           echo "AKS_RG='${{ secrets.AKS_RG }}'"
           echo "AKS_NAME='${{ secrets.AKS_NAME }}'"

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_NAME }} \
            --overwrite-existing

      - name: Create / Update DB secrets
        run: |
          kubectl create secret generic db-secrets \
            --from-literal=host=${{ secrets.DB_HOST }} \
            --from-literal=port=${{ secrets.DB_PORT }} \
            --from-literal=name=${{ secrets.DB_NAME }} \
            --from-literal=user=${{ secrets.DB_USER }} \
            --from-literal=password=${{ secrets.DB_PASSWORD }} \
            --from-literal=sslmode=${{ secrets.DB_SSLMODE }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/financial-decision-system \
            pipeline=${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/financial-decision-system